### ISSUE TITLE
Trying to understand working of plugin 

### ISSUE THREAD

**Issue by cchandel** [nohal/objsearch_pi#14]
Hi,
  I'm trying to understand the code to figure out how to access soundings.

  I see that the Insert query is in StoreNewFeature which gets called by SendVectorChartObjectInfo. This is in turn only called by the CSV processing functions.

  Also, ScanArea scans all charts, but how does StoreNewFeature get called after a new chart is loaded ?

  I couldn't find much about the API - hence asking for help.

Thanks.

**Comment by nohal** [comment]
`SendVectorChartObjectInfo` is invoked by the OpenCPN core via https://github.com/OpenCPN/OpenCPN/blob/master/src/pluginmanager.cpp#L1424
Scanning an area means the plugin asks the core to move the viewport, which (should) lead to loading of new charts, which leads to actually invoking the above.

Said all that, this functionality is not usable to get access to soundings data, so if you need that, you need to use a different (currently unimplemented) approach.
