### ISSUE TITLE
When objsearch is enabled

### ISSUE THREAD

**Issue by rgleason** [nohal/objsearch_pi#19]
**Describe the bug**
All plugins show green puzzles in the Options > PIM

**To Reproduce**
1. Install the plugin
2. To fix this condition.  Remove ObjSearch.
3. Close Opencpn
4. When Opencpn loads there is a message that Objsearch is being removed due to incompatible.
5. Also I did not see the plugin icon in the toolbar and looked in several places for where to enter a search.
[opencpn.log (2).txt](https://github.com/nohal/objsearch_pi/files/10985767/opencpn.log.2.txt)

*Desktop (please complete the following information if applicable):**
 - OS: Win 11
 - Version most current build using VX   5.71

**Smartphone/Tablet (please complete the following information if applicable):**
 - Device: [e.g. Galaxy S20]
 - Andorid version: [e.g. 10]

**Additional context**
Very nice to see this one being added back in!

**Comment by nohal** [comment]
The Windows build was erroneously done as Debug instead of Release, new version in the pipeline.

**Comment by rgleason** [comment]
thnks
