### ISSUE TITLE
Installation on Debian 12 crashes Opencpn

### ISSUE THREAD

**Issue by leamas** [nohal/objsearch_pi#27]
**Describe the bug**
After CLI installation of Objsearch OpenCPN terminates and plugin must be manually removed.

**To Reproduce**
1. `opencpn-cmd install-plugin ObjSearch`
2. `opencpn-cmd list-plugins`
3. See error message `terminate called after throwing an instance of 'wxSQLite3Exception'`

**Expected behavior**
The plugin should be installed and commands such as  `list-plugins` and `uninstall-plugin` should work

**Desktop (please complete the following information if applicable):**
 - Debian 12 Bookworm, x86_64

**Additional context**
I have installed all available plugins, this is the only one which cannot be installed, listed and uninstalled using the CLI. 
I'm worried about the un-caught exception which probably has potential to bite us in other contexts.

**Comment by nohal** [comment]
What does `opencpn-cmd` do that normal OpenCPN does not? I'm just looking at the plugin working just fine on both my arm64 and x86_64 Bookworm...

**Comment by leamas** [comment]
Yes, it works just fine when installed from the GUI.

It might be that base_platform isn't initiated so the plugin does not get the data directory it needs. Will look into this tomorrow. But even so, it should not throw an exception and terminate application.

**Comment by nohal** [comment]
I suppose all this is going to be resolved by simply moving stuff away from the constructor to `::Init`, but yes, this old codebase would certainly deserve being made more robust.

**Comment by nohal** [comment]
At first sight I don't see unhandled `wxSQLite3Exception`, but evidently there must be some somewhere

**Comment by nohal** [comment]
ah, already fixed for next release in https://github.com/nohal/objsearch_pi/commit/395e90e43d2bde67e7efe6a962959cd8c49ddedf
