### ISSUE TITLE
Database i/o fails in Windows 10

### ISSUE THREAD

**Issue by mmikkone** [nohal/objsearch_pi#3]
From log file:

9:14:27 AM: OBJSEARCH_PI: Database file to be used: C:\ProgramData\opencpn\objsearch_pi.db

9:15:28 AM: OBJSEARCH_PI: DB Exception: 10 : disk I/O error[266]: disk I/O error

The database seems to be OK, when browsed with SqLiteBrowser.
Perhaps the error occurs because of the extra '\' in the path?

[objsearch_pi.zip](https://github.com/nohal/objsearch_pi/files/292791/objsearch_pi.zip)

[opencpn.zip](https://github.com/nohal/objsearch_pi/files/292790/opencpn.zip)

**Comment by rgleason** [comment]
ObjSearch  0.7 in O v4.2.1
ObjSearch 0.7 in O v4.2.1724
ObjSearch 0.7 in O v4.2.0

Set the search distance at the bottom to "0"  unlimited

CM93 charts search on Saint-Cast-le-Guildo
CM93 charts search on Saint-Malo
CM93 charts search on Newport
CM93 charts search on Watch Hill reef
Rnc Charts search on same items as above.

All work just fine in Windows 10

**Comment by nohal** [comment]
I also can't reproduce.
If still present with 0.8, please try shut down OpenCPN, move the current database file away and start with a clean table. Reopen if it won't help.
